- directory: ./img/videos/*.*
  width: 240
  height: 240

- directory: ./img/mentors/*.*
  width: 240
  height: 240

- directory: ./img/projects/*.*
  width: 240
  height: 500

- directory: ./img/students/*.*
  width: 240
  height: 240

- directory: ./img/team/*.*
  width: 240
  height: 240
